spring:
  application.name: turbine
security.basic.enabled: false
turbine:
  aggregator:
    clusterConfig: SAMPLE
  appConfig: recommendations,membership
  clusterNameExpression: appGroupName
eureka.client.serviceUrl.defaultZone: http://localhost:9000/eureka/
server.port: 9002